[package]
name = "data-model-rust-samples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# git source should be in sync with the ref used for data-model compilation
iroha_data_model = { git = 'https://github.com/appetrosyan/iroha.git', branch = "iroha2-staging" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parity-scale-codec = "3.2.1"
