[package]
name = "iroha_crypto_wasm"
version = "0.2.0"
authors = ["0x009922"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = "0.4"
ursa = { version = "=0.3.5", default-features = false, features = ["portable"] }

derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "display"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive", "full"] }
serde = { version = "1", default-features = false, features = ["derive"] }
hex = { version = "0.4", default-features = false, features = ["alloc", "serde"] }
const-str = {version = "0.5.3", features = ["proc"]}

iroha_primitives = { path = "../../iroha-source/.iroha/primitives", default-features = false }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
hex-literal = "0.2.1"
serde_json = "1.0"

[patch.crates-io]
aesni = { git = "https://github.com/RustCrypto/block-ciphers", tag = "aesni-v0.7.0" }
aes-soft = { git = "https://github.com/RustCrypto/block-ciphers", tag = "aes-soft-v0.4.0" }
