name: Pull Request CI
on:
  pull_request:
    branches: [main]
jobs:
  prep-crypto-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
         cache: 'false'
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/cache@v4
        name: prep-cache
        with:
          path: |
            prep/crypto-wasm
          key: ${{ runner.os }}-{{ hashFiles('crypto-wasm/*') }}
      - name: Build packages
        if: steps.prep-cache.outputs.cache-hit != 'true'
        run: deno task prep:crypto-wasm

  check:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.13.1'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Clone Iroha
        run: deno task prep:iroha --git $IROHA_GIT --git-rev $IROHA_REV
        env:
          IROHA_GIT: https://github.com/0x009922/iroha.git
          IROHA_REV: 5302-expose-signature-payload

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'nightly-2024-09-09,stable'
          target: 'wasm32-unknown-unknown'
          components: rust-src
          cache: 'false'

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ".iroha -> target\n.iroha/wasm -> target\ncrypto-wasm -> target"
          cache-on-failure: 'true'
          cache-all-crates: 'true'

      - name: Prep tasks
        run: |
          deno task prep:iroha:build
          deno task prep:crypto-wasm
          deno task prep:codegen

      - name: Type check
        run: deno task check:all

      - name: Lint, format
        run: |
          deno lint
          deno fmt --check

      - name: Test
        run: deno task test
